# Generated by Django 2.1.4 on 2018-12-18 04:54

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/frontpage/')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '910x350', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vieworder', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['vieworder'],
            },
        ),
        migrations.CreateModel(
            name='GHGEnergyMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meter', models.IntegerField(default=100)),
                ('interval', models.IntegerField()),
                ('Kt', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('program', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('photo', models.ImageField(upload_to='images/people/')),
                ('cropping', image_cropping.fields.ImageRatioField('photo', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('cv', models.FileField(blank=True, upload_to='files/cv/')),
                ('emailuser', models.CharField(max_length=255)),
                ('emaildomain', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('viewable', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vieworder', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['vieworder'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('weblink', models.URLField(blank=True)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('pubdate', models.DateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('about', models.TextField()),
                ('grants', models.CharField(blank=True, max_length=255)),
                ('videoURL', models.URLField(blank=True)),
                ('thumb', models.ImageField(upload_to='images/projects/thumbs/')),
                ('cropping', image_cropping.fields.ImageRatioField('thumb', '172x172', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('projectCrop', image_cropping.fields.ImageRatioField('thumb', '250x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='projectCrop')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('exhibit', models.BooleanField(default=False)),
                ('viewable', models.BooleanField(default=True)),
                ('vieworder', models.IntegerField(default=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vieworder'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('journal', models.CharField(max_length=255)),
                ('pages', models.CharField(blank=True, max_length=255)),
                ('award', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('viewable', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('localCopy', models.FileField(blank=True, upload_to='files/pubs/')),
                ('weblink', models.URLField(blank=True)),
                ('pubType', models.CharField(choices=[('journal', 'Journal Articles'), ('book', 'Book Chapters'), ('refConfs', 'Refereed Conference Papers'), ('presentations', 'Presentations and Posters'), ('workshops', 'Workshop Papers'), ('others', 'Other Papers')], max_length=255)),
                ('pubAffil', models.CharField(choices=[('lab', 'TIDAL Lab'), ('personal', 'Personal')], max_length=255)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
